/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorControls: typeof import('./../components/ColorControls.vue')['default']
    ColorPicker: typeof import('./../components/ColorPicker.vue')['default']
    Command: typeof import('./../components/Command.vue')['default']
    CommandOutput: typeof import('./../components/CommandOutput.vue')['default']
    Editor: typeof import('../components/SignEditor.vue')['default']
    EditorToolbar: typeof import('./../components/EditorToolbar.vue')['default']
    SignEditor: typeof import('./../components/SignEditor.vue')['default']
    SignEditors: typeof import('./../components/SignEditors.vue')['default']
    SignLabel: typeof import('./../components/SignLabel.vue')['default']
    SignTypeSelect: typeof import('./../components/SignTypeSelect.vue')['default']
  }
}
