# TELL IF NO PERMISSION
    execute if entity @s[tag=!wpm_OP] run tellraw @s ["",{"text":"You do not have permission\nto perform this action!","color":"red"}]


################################ BUILDING ITEMS ##############################
execute if score @s _get_wpm_item_ID matches 1000000 if entity @s[tag=wpm_OP] run function wpm:map_funcs/get_items/all_building

execute if score @s _get_wpm_item_ID matches 1000001 if entity @s[tag=wpm_OP] run give @s enderman_spawn_egg{Enchantments:[{}],Tags:["DELETER_Spawnegg"],EntityTag:{id:"interaction",height:.25f,width:.25f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","DELETER","Play_Particles"]},display:{Name:'[{"text":"DELETER","color":"#FF3A45","bold":true}]',Lore:['[{"text":"place on or next to a special","color":"#CD2A33"}]','[{"text":"parkour-map block to delete it","color":"#CD2A33"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000002 if entity @s[tag=wpm_OP] run give @s allay_spawn_egg{Enchantments:[{}],Tags:["AirLift_Spawnegg"],EntityTag:{id:"interaction",height:5f,width:.4f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","AirLift"]},display:{Name:'[{"text":"Air Lift","bold":true,"color":"#99CCFF"}]',Lore:['[{"text":"An invisible (10 blocks) lift","color":"#66CCFF"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000003 if entity @s[tag=wpm_OP] run give @s creeper_spawn_egg{Enchantments:[{}],Tags:["JumpPad_Spawnegg"],EntityTag:{id:"interaction",height:1f,width:.4f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","JumpPad"]},display:{Name:'[{"text":"Jump Pad","color":"#00CC66","bold":true}]',Lore:['[{"text":"An invisible jump booster","color":"#66CC99"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000004 if entity @s[tag=wpm_OP] run give @s elder_guardian_spawn_egg{Enchantments:[{}],Tags:["Portal1_Spawnegg"],EntityTag:{id:"interaction",height:2f,width:1.01f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","PORTAL","Portal1"]},display:{Name:'[{"text":"Portal","color":"blue","bold":true},{"text":" 1","color":"gold"}]',Lore:['[{"text":"Teleports players to ","color":"#CC33FF"},{"text":"Portal ","color":"yellow","bold":true},{"text":"2","color":"gold","bold":true}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000005 if entity @s[tag=wpm_OP] run give @s elder_guardian_spawn_egg{Enchantments:[{}],Tags:["Portal2_Spawnegg"],EntityTag:{id:"interaction",height:2f,width:1.01f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","PORTAL","Portal2"]},display:{Name:'[{"text":"Portal","color":"yellow","bold":true},{"text":" 2","color":"gold"}]',Lore:['[{"text":"Teleports players to ","color":"#CC33FF"},{"text":"Portal ","color":"blue","bold":true},{"text":"1","color":"gold","bold":true}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000006 if entity @s[tag=wpm_OP] run give @s blaze_spawn_egg{Enchantments:[{}],Tags:["ResetButton_Spawnegg"],EntityTag:{id:"interaction",height:0f,width:.25f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","ResetButton"],CustomName:'[{"text":"Reset","bold":true,"color":"gold"}]',CustomNameVisible:1b},display:{Name:'[{"text":"Reset Button","bold":true,"color":"gold"}]',Lore:['[{"text":"Resets players back to","color":"#D58D17"}]','[{"text":"their last checkpoint","color":"#D58D17"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000007 if entity @s[tag=wpm_OP] run give @s ender_dragon_spawn_egg{Enchantments:[{}],Tags:["FakePortal_Spawnegg"],EntityTag:{id:"interaction",height:1f,width:1f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","Fake_Portal"]},display:{Name:'[{"text":"Fake Portal","color":"#9900FF","bold":true}]',Lore:['[{"text":"Places a fake portal","color":"#9966FF"}]','[{"text":"for decoration","color":"#9966FF"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000008 if entity @s[tag=wpm_OP] run give @s wandering_trader_spawn_egg{Enchantments:[{}],Tags:["SnakeBlock_Spawnegg"],EntityTag:{id:"interaction",height:.25f,width:.25f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","Snake_Block"]},display:{Name:'[{"text":"Snake Block","bold":true,"color":"#2461B4"}]',Lore:['[{"text":"Spawns a block that forms","color":"#6699FF"}]','[{"text":"a moving snake with other","color":"#6699FF"}]','[{"text":"such blocks next to it.","color":"#6699FF"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000009 if entity @s[tag=wpm_OP] run give @s turtle_spawn_egg{Enchantments:[{}],Tags:["MovingPlatform_Spawnegg"],EntityTag:{id:"interaction",height:1f,width:1f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","_MovingPlatform_","MovingPlatform"]},display:{Name:'[{"text":"Moving Platform","bold":true,"color":"#00BBE0"}]',Lore:['[{"text":"Spawns a platform, which","color":"#44ACDD"}]','[{"text":"moves up and down.","color":"#44ACDD"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000010 if entity @s[tag=wpm_OP] run give @s panda_spawn_egg{Enchantments:[{}],Tags:["DisplayItem_Spawnegg"],EntityTag:{id:"interaction",height:1.01f,width:1.01f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","Display_item"]},display:{Name:'[{"text":"Display Item","color":"#ABADCD","bold":true},{"text":" "},{"text":"Connector","color":"#7E88EC"}]',Lore:['[{"text":"Place within a radius of 1.5 blocks","color":"#5665F0"}]','[{"text":"of an item lying on the ground to","color":"#5665F0"}]','[{"text":"turn it into a display item","color":"#5665F0"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000011 if entity @s[tag=wpm_OP] run give @s strider_spawn_egg{Enchantments:[{}],Tags:["INT-Lock_Spawnegg"],EntityTag:{id:"interaction",height:1.01f,width:1.01f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","INT_Lock","Visible","Play_Particles"]},display:{Name:'[{"text":"VISIBLE ","color":"#7878C0"},{"text":"Interaction ","color":"#FF4853","bold":true},{"text":"Lock","color":"#E5182E"}]',Lore:['[{"text":"Can be placed on top of (above) functional blocks","color":"#990033"}]','[{"text":"to prevent players from interacting with them","color":"#990033"}]','[{"text":""}]','[{"text":"VISIBLE","color":"#FF6666","bold":true},{"text":" "},{"text":"= Says «Locked» on interaction.","color":"#E34354"}]']}} 1
execute if score @s _get_wpm_item_ID matches 1000012 if entity @s[tag=wpm_OP] run give @s strider_spawn_egg{Enchantments:[{}],Tags:["INT-Lock_Spawnegg"],EntityTag:{id:"interaction",height:1.01f,width:1.01f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","INT_Lock","Invisible","Play_Particles"]},display:{Name:'[{"text":"INVISIBLE ","color":"#7878C0"},{"text":"Interaction ","color":"#FF4853","bold":true},{"text":"Lock","color":"#E5182E"}]',Lore:['[{"text":"Can be placed on top of (above) functional blocks","color":"#990033"}]','[{"text":"to prevent players from interacting with them","color":"#990033"}]','[{"text":""}]','[{"text":"INVISIBLE","color":"#FF6666","bold":true},{"text":" "},{"text":"= Just blocks the interaction.","color":"#E34354"}]']}} 1

execute if score @s _get_wpm_item_ID matches 1000013 if entity @s[tag=wpm_OP] run give @s light_weighted_pressure_plate{display:{Name:'[{"text":"Checkpoint","color":"gold","bold":true}]'}} 1
execute if score @s _get_wpm_item_ID matches 1000014 if entity @s[tag=wpm_OP] run give @s warped_pressure_plate{display:{Name:'[{"text":"Gamemode","color":"#666699","bold":true},{"text":" PARKOUR","color":"#339999"}]'}} 1
execute if score @s _get_wpm_item_ID matches 1000015 if entity @s[tag=wpm_OP] run give @s mangrove_pressure_plate{display:{Name:'[{"text":"Gamemode","color":"#666699","bold":true},{"text":" RESET","color":"#CC4631"}]'}} 1

execute if score @s _get_wpm_item_ID matches 1000016 if entity @s[tag=wpm_OP] run give @s light{BlockStateTag:{level:"0"},display:{Name:'[{"text":"DeathBlock","color":"dark_red","bold":true},{"text":" INVIS.","color":"#666699"}]'}} 1
execute if score @s _get_wpm_item_ID matches 1000017 if entity @s[tag=wpm_OP] run give @s light{BlockStateTag:{level:"1"},display:{Name:'[{"text":"AirLift ","color":"#99CCFF","bold":true},{"text":"INTERACTOR","color":"#666699"}]'}} 1
execute if score @s _get_wpm_item_ID matches 1000018 if entity @s[tag=wpm_OP] run give @s light{BlockStateTag:{level:"2"},display:{Name:'[{"text":"JumpPad ","color":"#83FF00","bold":true},{"text":"INTERACTOR","color":"#666699"}]'}} 1


################################ BUY STATIONS ##############################
execute if score @s _get_wpm_item_ID matches 2000000 if entity @s[tag=wpm_OP] run function wpm:map_funcs/get_items/all_buy-stations

execute if score @s _get_wpm_item_ID matches 2000001 if entity @s[tag=wpm_OP] run give @s magma_cube_spawn_egg{Enchantments:[{}],Tags:["BuyStation_Spawnegg"],EntityTag:{id:"interaction",height:0f,width:1f,Rotation:[0f,0f],Invulnerable:1b,Tags:["NEW","BuyStation","Buy_FreezeBomb"]},display:{Name:'[{"text":"BUY STATION:","bold":true,"color":"#F7E83B"},{"text":" Freeze Bomb","color":"aqua"}]',Lore:['[{"text":"A station for players","color":"#CEC344"}]','[{"text":"to buy this item   ⤴","color":"#CEC344"}]']}} 1


################################ RACE ITEMS ##############################
execute if score @s _get_wpm_item_ID matches 3000000 if entity @s[tag=wpm_OP] run function wpm:map_funcs/get_items/all_raceitems

execute if score @s _get_wpm_item_ID matches 3000001 if entity @s[tag=wpm_OP] run give @s red_candle{CustomModelData:2560001,Enchantments:[{id:"infinity",lvl:1}],Unbreakable:1,Tags:["SlapStick"],EntityTag:{Invisible:1b},AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:-1,Slot:mainhand,Name:"generic.attack_damage",UUID:[I;-123710,28282,1024,-56564]}],display:{Name:'[{"text":"SLAP STICK","color":"#FFCC00"},{"text":" [","color":"#BBBBBB"},{"text":"ᴀᴄᴛɪᴠᴇ","color":"#66CC66"},{"text":"][","color":"#BBBBBB"},{"text":"INACTIVE","color":"#FF6666","bold":true},{"text":"]","color":"#BBBBBB"}]',Lore:['[{"text":"If active:","color":"#888888","bold":true},{"text":" gives your opponent","color":"#888888"}]','[{"text":"  → ","color":"#888888"},{"text":"knockback","color":"dark_purple"},{"text":" but still ","color":"888888"},{"text":"0 damage","color":"dark_purple"},{"text":"","color":"dark_purple"}]','[{"text":"","color":"dark_purple"}]','[{"text":"‹< active every ","color":"gray"},{"text":"20s","color":"light_purple"},{"text":" for "},{"text":"10s","color":"light_purple"},{"text":" >›"}]']},HideFlags:35} 1
execute if score @s _get_wpm_item_ID matches 3000002 if entity @s[tag=wpm_OP] run give @s golden_shovel{CustomModelData:2560001,Damage:12,EntityTag:{Invisible:1b},AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:7.5,Slot:mainhand,Name:"generic.attack_damage",UUID:[I;-1231114,24295,125612,-48590]}],display:{Name:'[{"text":"THROW ","color":"#FFCC00","bold":true},{"text":"Shovel"}]',Lore:['[{"text":"It will throw your opponent","color":"gold"}]','[{"text":"pretty far from his path.","color":"gold"},{"text":"","color":"dark_purple"}]','[{"text":"","color":"dark_purple"}]','[{"text":"〚10 uses before it breaks〛","color":"blue"}]']},Enchantments:[{id:"knockback",lvl:4}],HideFlags:35} 1
execute if score @s _get_wpm_item_ID matches 3000003 if entity @s[tag=wpm_OP] run give @s bow{CustomModelData:2560001,Unbreakable:1,EntityTag:{Invisible:1b},display:{Name:'[{"text":"Arrow","color":"#99CCCC","bold":true},{"text":" Launcher"}]',Lore:['[{"text":"Launches arrows ","color":"#6699CC"},{"text":"pretty far","color":"dark_purple"},{"text":" and","color":"#6699CC"}]','[{"text":"in addition, ","color":"#6699CC"},{"text":"throws the hit player","color":"light_purple"}]']},Enchantments:[{id:"infinity",lvl:1},{id:"punch",lvl:1},{id:"quick_charge",lvl:255}],HideFlags:35} 1
execute if score @s _get_wpm_item_ID matches 3000004 if entity @s[tag=wpm_OP] run give @s warped_fungus_on_a_stick{CustomModelData:2560001,Unbreakable:1,Damage:0,Tags:["Homing_MissileLauncher"],tags:1b,EntityTag:{Invisible:1b},display:{Name:'[{"text":"HOMING","color":"#FF6633"},{"text":" ","color":"#669999"},{"text":"Missile-Launcher","color":"#26D8A8","bold":true}]',Lore:['[{"text":"Launches a ","color":"#66CCCC"},{"text":"FUNGUS-MISSILE","color":"#00CCCC"},{"text":"","color":"dark_purple"}]','[{"text":"when right-clicked.","color":"#66CCCC"}]','[{"text":"The ","color":"#66CCCC"},{"text":"MISSILE","color":"#00CCCC"},{"text":" will fly in the","color":"#66CCCC"}]','[{"text":"direction you\'re looking and","color":"#66CCCC"}]','[{"text":"start ","color":"#66CCCC"},{"text":"HOMING","color":"#00CCCC"},{"text":" an entity when","color":"#66CCCC"}]','[{"text":"it ","color":"#66CCCC"},{"text":"COMES CLOSE ENOUGH","color":"#00CCCC"},{"text":" to one."},{"text":"","color":"dark_purple"}]','[{"text":"","color":"dark_purple"}]','[{"text":"Much Damage","color":"#6699FF"}]']},Enchantments:[{id:"infinity",lvl:1}],HideFlags:99} 1
execute if score @s _get_wpm_item_ID matches 3000005 if entity @s[tag=wpm_OP] run give @s snowball{CustomModelData:2560001,Enchantments:[{id:"infinity",lvl:1}],HideFlags:1,Tags:["FreezeBomb"],display:{Name:'[{"text":"Freeze Bomb","bold":true,"color":"aqua"}]',Lore:['[{"text":"Freezes all entities in","color":"#CCFFFF"}]','[{"text":"a radius of 5 blocks to","color":"#CCFFFF"}]','[{"text":"the ","color":"#CCFFFF"},{"text":"Freeze Bomb","color":"aqua"},{"text":"."},{"text":"","color":"dark_purple"}]','[{"text":"","color":"dark_purple"}]','[{"text":"No Damage","color":"#6699FF"},{"text":"","color":"dark_purple"}]','[{"text":"10s Freezing","color":"#66CCFF"}]']}} 1
execute if score @s _get_wpm_item_ID matches 3000006 if entity @s[tag=wpm_OP] run give @s mooshroom_spawn_egg{CustomModelData:2560001,HideFlags:17,Rotation:[0f,0f],CanPlaceOn:["#wpm:full_blocks","#trapdoors[half=top,open=false]","#slabs[type=double]","#stairs[half=top]","#slabs[type=top]"],EntityTag:{id:"interaction",height:1f,width:1f,Invulnerable:1b,Tags:["Landmine"],CustomName:'[{"text":"Landmine","color":"red","bold":true}]'},Enchantments:[{id:"infinity",lvl:1}],display:{Name:'[{"text":"Landmine","color":"red","bold":true}]',Lore:['[{"text":"Explodes on every ","color":"#CC3333"},{"text":"mob","color":"#FF6666"}]','[{"text":"and player","color":"#FF6666"},{"text":" ","color":"#CC3333"},{"text":"except you","color":"#FF0033"}]','[{"text":"that comes in a ","color":"#CC3333"},{"text":"radius","color":"#FF6666"}]','[{"text":"of 1 block","color":"#FF6666"},{"text":" to the mine","color":"#CC3333"}]','[{"text":""}]','[{"text":"Much Damage","color":"#FF9966"}]','[{"text":"Infinite Life Time","color":"#FF9900"}]','[{"text":""}]','[{"text":"Can be placed on:","color":"#BBBBBB"},{"text":"","color":"dark_purple"}]','[{"text":"All Full Blocks","color":"#666666"}]']}} 1


# CHECK INVALID ID
    execute if score @s _get_wpm_item_ID matches 1000000..1000018 run tag @s add ID_found
    execute if score @s _get_wpm_item_ID matches 2000000..2000001 run tag @s add ID_found
    execute if score @s _get_wpm_item_ID matches 3000000..3000006 run tag @s add ID_found
    # ANNOUNCE FAILED ITEM-RESOLVE
        execute unless entity @s[tag=ID_found] run function wpm:map_funcs/get_items/by_id/announce_no-id

# RESET GET-ITEM-BY-ID
    function wpm:map_funcs/get_items/by_id/reset_get-item
